# version: "3.9"

services:
  ollama:
    image: ollama/ollama
    container_name: ollama
    volumes:
      - ollama_volume:/root/.ollama
    ports:
      - "11434:11434"

  api:
    build: .
    container_name: fast-api-ai
    depends_on:
      - ollama
    environment:
      OLLAMA_BASE_URL: http://ollama:11434
    ports:
      - "127.0.0.1:8000:8000"
    volumes:
      - ./backend/data:/app/data
      - ./backend/chroma_db:/app/chroma_db

  portainer:
    container_name: portainer
    image: portainer/portainer-ce:latest #:lts
    restart: always
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer_data:/data
    ports:
      - "127.0.0.1:9443:9443"
      # - 8000:8000  # Remove if you do not intend to use Edge Agents

volumes:
  ollama_volume:
  portainer_data:
